### ISSUE TITLE
Application falls into an infinite loop in a specific case

### ISSUE THREAD

**Issue by David-Delgadillo** [Pando65/proyectoAppFisica#2]
This happens when the user inserts a 0 in both velocity and acceleration. Omar you could try maybe to cut the number of seconds to 500 seconds.

**Comment by David-Delgadillo** [comment]
Omar, también intercambia las gráficas bofo. El de posición va arriba y el de velocidad abajo.

**Comment by Pando65** [comment]
creo que se debería validar desde antes del botón graficar, si ambos son 0 ps dile no chavo, tu carro no se va a mover :v 

cambiar el orden de las graficas es solo mover los views, lo hago en corto

**Comment by Pando65** [comment]
Resuelto
